/*
 Copyright (c) 2023 RobeeContech, Inc.
 Author: Yoav Fekete
*/

#ifndef HARDWARE_INTERFACE_WRAPPERS__VISIBILITY_CONTROL_H_
#define HARDWARE_INTERFACE_WRAPPERS__VISIBILITY_CONTROL_H_

// This logic was borrowed (then namespaced) from the examples on the gcc wiki:
//     https://gcc.gnu.org/wiki/Visibility

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define HARDWARE_INTERFACE_WRAPPERS_EXPORT __attribute__((dllexport))
#define HARDWARE_INTERFACE_WRAPPERS_IMPORT __attribute__((dllimport))
#else
#define HARDWARE_INTERFACE_WRAPPERS_EXPORT __declspec(dllexport)
#define HARDWARE_INTERFACE_WRAPPERS_IMPORT __declspec(dllimport)
#endif
#ifdef HARDWARE_INTERFACE_WRAPPERS_BUILDING_DLL
#define HARDWARE_INTERFACE_WRAPPERS_PUBLIC HARDWARE_INTERFACE_WRAPPERS_EXPORT
#else
#define HARDWARE_INTERFACE_WRAPPERS_PUBLIC HARDWARE_INTERFACE_WRAPPERS_IMPORT
#endif
#define HARDWARE_INTERFACE_WRAPPERS_PUBLIC_TYPE HARDWARE_INTERFACE_WRAPPERS_PUBLIC
#define HARDWARE_INTERFACE_WRAPPERS_LOCAL
#else
#define HARDWARE_INTERFACE_WRAPPERS_EXPORT __attribute__((visibility("default")))
#define HARDWARE_INTERFACE_WRAPPERS_IMPORT
#if __GNUC__ >= 4
#define HARDWARE_INTERFACE_WRAPPERS_PUBLIC __attribute__((visibility("default")))
#define HARDWARE_INTERFACE_WRAPPERS_LOCAL __attribute__((visibility("hidden")))
#else
#define HARDWARE_INTERFACE_WRAPPERS_PUBLIC
#define HARDWARE_INTERFACE_WRAPPERS_LOCAL
#endif
#define HARDWARE_INTERFACE_WRAPPERS_PUBLIC_TYPE
#endif

#endif  // HARDWARE_INTERFACE_WRAPPERS__VISIBILITY_CONTROL_H_